FROM cassandra:4.0
LABEL description="Cassandra + k8s readiness probe"

RUN \
  curl https://raw.githubusercontent.com/hexinw/bbx/master/docker/ready_probe.sh \
  -o /ready_probe.sh -s && chmod +x /ready_probe.sh
